### ISSUE TITLE
Write a function to decrypt the atbash cipher

### ISSUE THREAD

**Issue by preethika-ajay** [preethika-ajay/Ciphers#35]
# Write a function to decrypt the atbash cipher
## Description
Write a function to decrypt the atbash cipher.
## Prefered Implementation
void atbash::decrypt_atbash(); (this is the required prototype for the function)<br>

<hr>
Bounty points alloted : 30<br>
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by s-air-a** [comment]
Hey, could I please be assigned to this?

**Comment by preethika-ajay** [comment]
> Hey, could I please be assigned to this?

Sure!

**Comment by anushkaguptaaa** [comment]
Hello maintainer!! 
Would love to work on this issue. Can you please assign it??

**Comment by preethika-ajay** [comment]
> Hello maintainer!! Would love to work on this issue. Can you please assign it??

sure

**Comment by anushkaguptaaa** [comment]
Thank you!!

**Comment by Nischal1729** [comment]
Hello, I'd like to work on this issue. Please assign, thank you.

**Comment by preethika-ajay** [comment]
> Hello, I'd like to work on this issue. Please assign, thank you.

sure

**Comment by shr218** [comment]
hey! Can i work on this?

**Comment by preethika-ajay** [comment]
> hey! Can i work on this?

sure!
